language: node_js
node_js: lts/*
before_script:
  - "npm run build"
after_success:
  - "npm run coveralls"
jobs:
  include:
    - stage: test
      script: "npm run test:lint"
    - stage: test
      script: "npm run test:coverage"
    - stage: test
      script: "npm run test:security"
    - stage: test
      script: "npm run test:package"
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
notifications:
  email:
    recipients: dipustovit@gmail.com
    on_success: change
    on_failure: always